C
C.... Table Fullrecon.
#ifdef LONG_POINTER
      Integer*8 Fullrecon
#else
      Integer*4 Fullrecon
#endif
      External  Fullrecon
C
      Integer*4    Fullrecon_ID(1)
      Equivalence( PNT_Common(2),
     +             Fullrecon_ID )
      Integer*4    Fullrecon_FullBrec(1)
      Equivalence( PNT_Common(3),
     +             Fullrecon_FullBrec )
      Integer*4    Fullrecon_kind(1)
      Equivalence( PNT_Common(4),
     +             Fullrecon_kind )
      Integer*4    Fullrecon_b_mode(1)
      Equivalence( PNT_Common(5),
     +             Fullrecon_b_mode )
      Integer*4    Fullrecon_sub0_mode(1)
      Equivalence( PNT_Common(6),
     +             Fullrecon_sub0_mode )
      Integer*4    Fullrecon_sub1_mode(1)
      Equivalence( PNT_Common(7),
     +             Fullrecon_sub1_mode )
      Real*4       Fullrecon_deltE(1)
      Equivalence( PNT_Common(8),
     +             Fullrecon_deltE )
      Real*4       Fullrecon_Mbc(1)
      Equivalence( PNT_Common(9),
     +             Fullrecon_Mbc )
      Real*4       Fullrecon_Aux0(1)
      Equivalence( PNT_Common(10),
     +             Fullrecon_Aux0 )
      Real*4       Fullrecon_Aux1(1)
      Equivalence( PNT_Common(11),
     +             Fullrecon_Aux1 )
      Real*4       Fullrecon_Aux2(1)
      Equivalence( PNT_Common(12),
     +             Fullrecon_Aux2 )
      Real*4       Fullrecon_Aux3(1)
      Equivalence( PNT_Common(13),
     +             Fullrecon_Aux3 )
      Real*4       Fullrecon_Aux4(1)
      Equivalence( PNT_Common(14),
     +             Fullrecon_Aux4 )
      Real*4       Fullrecon_Aux5(1)
      Equivalence( PNT_Common(15),
     +             Fullrecon_Aux5 )
      Real*4       Fullrecon_Aux6(1)
      Equivalence( PNT_Common(16),
     +             Fullrecon_Aux6 )
      Real*4       Fullrecon_Aux7(1)
      Equivalence( PNT_Common(17),
     +             Fullrecon_Aux7 )
      Real*4       Fullrecon_Aux8(1)
      Equivalence( PNT_Common(18),
     +             Fullrecon_Aux8 )
      Real*4       Fullrecon_Aux9(1)
      Equivalence( PNT_Common(19),
     +             Fullrecon_Aux9 )
      Integer*4    Fullrecon_flag0(1)
      Equivalence( PNT_Common(20),
     +             Fullrecon_flag0 )
      Integer*4    Fullrecon_flag1(1)
      Equivalence( PNT_Common(21),
     +             Fullrecon_flag1 )
      Integer*4    Fullrecon_flag2(1)
      Equivalence( PNT_Common(22),
     +             Fullrecon_flag2 )
      Integer*4    Fullrecon_flag3(1)
      Equivalence( PNT_Common(23),
     +             Fullrecon_flag3 )
      Integer*4    Fullrecon_flag4(1)
      Equivalence( PNT_Common(24),
     +             Fullrecon_flag4 )
C
