
LIB_PATH_LIST = $(packagedir)/lib/so $(packagedir)/lib $(BUILD_TOP_DIR)/lib/so $(BUILD_TOP_DIR)/lib

ifneq "$(BELLE_LIB_DIR)" ""
LIB_PATH_LIST += $(BELLE_LIB_DIR)/so $(BELLE_LIB_DIR)
endif

BELLE_LIBS = -l$(PACKAGE) -lkfitter -lkid -leid -lhelix -lmdst -lqqutil

LINK_ARGS = $(NOT_TARGETS) $(patsubst %,-L%,$(LIB_PATH_LIST)) $(BELLE_LIBS) \
	$(CLHEP_LIBS) $(FLIBS)

../bin/jpsiks.so:
